<?php

use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        // $this->call(UsersTableSeeder::class);
        DB::table('customer')->insert([
                'nickname'=>'張先生',
                'email'=>'admin@gmail.com',
                'account'=>'admin',
                'password'=>bcrypt('admin')
        ]);
        DB::table('customer')->insert([
                'nickname'=>'舒潔',
                'email'=>'wangwang@gmail.com',
                'account'=>'user01',
                'password'=>bcrypt('user01')
        ]);
        DB::table('customer')->insert([
                'nickname'=>'可立雅',
                'email'=>'coliya@gmail.com',
                'account'=>'user02',
                'password'=>bcrypt('user02')
        ]);

        DB::table('merchandise_category')->insert([
                'name'=>'服飾',
        ]);
        DB::table('merchandise_category')->insert([
                'name'=>'盥洗',
        ]);
        DB::table('merchandise_category')->insert([
                'name'=>'食品',
        ]);
        DB::table('merchandise_category')->insert([
                'name'=>'家電',
        ]);
        DB::table('merchandise_category')->insert([
                'name'=>'傢俱',
        ]);
        DB::table('merchandise_category')->insert([
                'name'=>'禮券',
        ]);
        DB::table('merchandise_category')->insert([
                'name'=>'嬰兒用品',
        ]);
        DB::table('merchandise_category')->insert([
                'name'=>'寵物用品',
        ]);
        DB::table('merchandise_category')->insert([
                'name'=>'生活小物',
        ]);

        DB::table('merchandise')->insert([
                'category'=>'服飾',
                'status'=>'S',
                'name'=>'原領上衣',
                'introduction'=>'好',
                'photo'=>'img\bg.jpg',
                'price'=>255,
                'remain_count'=>3,
                'customer_id'=>1,
        ]);
        DB::table('merchandise')->insert([
                'category'=>'服飾',
                'status'=>'S',
                'name'=>'上衣',
                'introduction'=>'好',
                'photo'=>'img\products-01.jpg',
                'price'=>255,
                'remain_count'=>3,
                'customer_id'=>1,
        ]);
        DB::table('merchandise')->insert([
                'category'=>'盥洗',
                'status'=>'S',
                'name'=>'牙膏',
                'introduction'=>'好',
                'photo'=>'img\products-02.jpg',
                'price'=>255,
                'remain_count'=>3,
                'customer_id'=>1,
        ]);
        DB::table('merchandise')->insert([
                'category'=>'盥洗',
                'status'=>'S',
                'name'=>'沐浴乳',
                'introduction'=>'好',
                'photo'=>'img\products-03.jpg',
                'price'=>255,
                'remain_count'=>3,
                'customer_id'=>2,
        ]);
        DB::table('merchandise')->insert([
                'category'=>'食品',
                'status'=>'S',
                'name'=>'咖啡',
                'introduction'=>'好',
                'photo'=>'',
                'price'=>255,
                'remain_count'=>3,
                'customer_id'=>2,
        ]);
        DB::table('merchandise')->insert([
                'category'=>'家電',
                'status'=>'S',
                'name'=>'風扇',
                'introduction'=>'好',
                'photo'=>'',
                'price'=>255,
                'remain_count'=>3,
                'customer_id'=>3,
        ]);
        DB::table('merchandise')->insert([
                'category'=>'傢俱',
                'status'=>'C',
                'name'=>'床',
                'introduction'=>'',
                'photo'=>'',
                'price'=>255,
                'remain_count'=>3,
                'customer_id'=>1,
        ]);
        DB::table('merchandise')->insert([
                'category'=>'禮券',
                'status'=>'S',
                'name'=>'禮券',
                'introduction'=>'好',
                'photo'=>'',
                'price'=>255,
                'remain_count'=>3,
                'customer_id'=>1,
        ]);
        DB::table('merchandise')->insert([
                'category'=>'服飾',
                'status'=>'C',
                'name'=>'',
                'introduction'=>'好',
                'photo'=>'',
                'price'=>255,
                'remain_count'=>3,
                'customer_id'=>2,
        ]);
        DB::table('merchandise')->insert([
                'category'=>'服飾',
                'status'=>'C',
                'name'=>'',
                'introduction'=>'好',
                'photo'=>'',
                'price'=>255,
                'remain_count'=>3,
                'customer_id'=>3,
        ]);
        DB::table('merchandise')->insert([
                'category'=>'服飾',
                'status'=>'S',
                'name'=>'裙',
                'introduction'=>'好',
                'photo'=>'',
                'price'=>255,
                'remain_count'=>3,
                'customer_id'=>1,
        ]);
        DB::table('merchandise')->insert([
                'category'=>'服飾',
                'status'=>'S',
                'name'=>'襯衫',
                'introduction'=>'好',
                'photo'=>'img\intro.jpg',
                'price'=>255,
                'remain_count'=>3,
                'customer_id'=>1,
        ]);
        DB::table('merchandise')->insert([
                'category'=>'服飾',
                'status'=>'C',
                'name'=>'',
                'introduction'=>'好',
                'photo'=>'img\products-01.jpg',
                'price'=>255,
                'remain_count'=>3,
                'customer_id'=>1,
        ]);
    }
}
